version: '3.7'
services:
  wg-dashboard:
    build: .
    image: hongkongkiwi/wg-dashboard
    volumes:
      - ./config/wg0.conf:/etc/wireguard/wg0.conf:rw
    environment:
      - TZ=Asia/Hong_Kong
    ports:
      - 3000:3000
      - 53:53
