version: '3.7'
services:
  wg-dashboard:
    build: .
    image: hongkongkiwi/wg-dashboard
    volumes:
      - ./wireguard:/etc/wireguard:rw
      - ./configs:/configs:rw
    environment:
      - TZ=Asia/Hong_Kong
      - NODE_ENV=development
    ports:
      - 3000:3000
      - 53:8053
    cap_add:
      - NET_ADMIN
