version: '3.7'
services:
  wg-dashboard:
    build: .
    image: hongkongkiwi/wg-dashboard
    volumes:
      - ./wireguard/wg0.conf:/etc/wireguard/wg0.conf:rw
      - ./config/server_config.json:/wg-dashboard/server_config.json:rw
      - ./config/coredns:/etc/coredns/Corefile:rw
    environment:
      - TZ=Asia/Hong_Kong
    ports:
      - 3000:3000
      - 53:8053
